### ISSUE TITLE
[Bug]: Police | Escorting | f8 quit

### ISSUE THREAD

**Issue by tiktokenjoyer** [armastudiosuk/issue-tracker#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This officer was bugged apparently, and he was escorting me and he wasn't able to release me, think it was a him issue, not a server issue, upon him giving up on options he decided to f8 quit. resulting my game crashing is there a fix for this?

Handcuffed me > Escorted me > Logged off > caused me to crash.

### Expected behaviour

Handcuffed me > Escorted me > Logged off > caused me to crash.

### Steps to reproduce

Handcuffed me > Escorted me > Logged off > caused me to crash.

### Any Texture Packs? (If so list)

no

### ARMA User ID

3476

**Comment by kwt** [comment]
It's to do with how the game handles entity attachments. After he disconnects because the Ped is no longer present your game crashes. May potentially be able to look into un escorting upon that player disconnecting but due to the time it would take to pass from server -> client will probably remain an issue. Just how FiveM is 🤷‍♂️
